AllCops:
  Exclude:
    - 'bin/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
