inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - features/**/*

Metrics/MethodLength:
  Max: 15

Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - features/**/*
