sudo: false
language: ruby
cache:
  bundler: true
before_install:
- gem update --system
notifications:
  slack:
    secure: AAOOmT8WC2VhlOAyxthZdbJlnpShzgo6HAOH+jyivKdgS5Na+GuNtEY45g5GCjBv7rlf8q+ZyG4tOwgnQ3ylB9f85B1HcGol+qnhs/0T787XjRVTOgPj6k2iFLUlwOBHhPE4oxpjXz6vp+gaqL5BlU4nYqG185tOp/SK/V3SWW8=
